"use server";import {createClient} from "@/lib/supabase/server";import {redirect} from "next/navigation";
import { businessProfiles, isPlausiblePhone } from "@/lib/landing-catalog";
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,60);
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
async function auth(){const s=await createClient();const {data,error}=await s.auth.getUser();if(error||!data.user)redirect("/admin/login");return {s,user:data.user}}
function checkClientFields(fd:FormData,onError:(message:string)=>never){const name=String(fd.get("name")||"").trim();if(!name)onError("El nombre del cliente es obligatorio.");const email=String(fd.get("email")||"").trim();if(email&&!emailPattern.test(email))onError("El email no parece válido. Revisalo y probá de nuevo.");const phone=String(fd.get("phone")||"").trim();if(phone&&!isPlausiblePhone(phone))onError("El WhatsApp parece incompleto. Escribilo con código de país, ej: 5493511234567.");return {name,email,phone}}
export async function newClient(fd:FormData){const {s,user}=await auth();const onError=(message:string):never=>redirect("/admin?error="+encodeURIComponent(message));const {name,email,phone}=checkClientFields(fd,onError);const {data,error}=await s.from("clients").insert({owner_id:user.id,name,email,phone,primary_color:String(fd.get("primary_color")||"#1f2937"),background_color:String(fd.get("background_color")||"#f7f5f0")}).select("id").single();if(error||!data)redirect("/admin?error="+encodeURIComponent(error?.message||"No se pudo crear el cliente"));redirect("/admin?success=Cliente creado correctamente")}
export async function updateClient(fd:FormData){const {s,user}=await auth();const id=String(fd.get("id"));const onError=(message:string):never=>redirect("/admin/clientes/"+id+"?error="+encodeURIComponent(message));const {name,email,phone}=checkClientFields(fd,onError);const {data:client,error:lookupError}=await s.from("clients").select("id").eq("id",id).eq("owner_id",user.id).maybeSingle();if(lookupError)onError(lookupError.message);if(!client)onError("Cliente inexistente o sin permisos");const {error}=await s.from("clients").update({name,email,phone,primary_color:String(fd.get("primary_color")||"#1f2937"),background_color:String(fd.get("background_color")||"#f7f5f0")}).eq("id",id).eq("owner_id",user.id);if(error)onError(error.message);redirect("/admin/clientes/"+id+"?saved=Cliente actualizado")}
export async function deleteClient(fd:FormData){const {s,user}=await auth();const id=String(fd.get("id")||"");const {data:client,error:lookupError}=await s.from("clients").select("id").eq("id",id).eq("owner_id",user.id).maybeSingle();if(lookupError)redirect("/admin?error="+encodeURIComponent(lookupError.message));if(!client)redirect("/admin?error=Cliente inexistente o sin permisos");const {error}=await s.from("clients").delete().eq("id",id).eq("owner_id",user.id);if(error)redirect("/admin?error="+encodeURIComponent(error.message));redirect("/admin?saved=Cliente eliminado; sus landings quedaron sin cliente")}
export async function newLanding(fd:FormData){const {s,user}=await auth();const businessName=String(fd.get("business_name")||"").trim();if(!businessName)redirect("/admin?error="+encodeURIComponent("El nombre de la landing es obligatorio."));let slug=slugify(String(fd.get("slug")||businessName));const {data:ex,error:slugError}=await s.from("landings").select("id").eq("slug",slug).maybeSingle();if(slugError)redirect("/admin?error="+encodeURIComponent(slugError.message));if(ex)slug+="-"+Math.floor(Math.random()*999);const clientId=String(fd.get("client_id")||"")||null;const businessType=String(fd.get("business_type")||"custom");if(!businessProfiles.some((profile)=>profile.value===businessType))redirect("/admin?error=Tipo de perfil inválido");const {data:client,error:clientError}=clientId?await s.from("clients").select("primary_color,background_color").eq("id",clientId).eq("owner_id",user.id).maybeSingle():{data:null,error:null};if(clientError)redirect("/admin?error="+encodeURIComponent(clientError.message));if(clientId&&!client)redirect("/admin?error=Cliente inexistente o sin permisos");const {data,error}=await s.from("landings").insert({owner_id:user.id,client_id:clientId,business_name:businessName,slug,template:String(fd.get("template")||"professional"),business_type:businessType,primary_color:client?.primary_color||"#1f2937",background_color:client?.background_color||"#f7f5f0"}).select("id").single();if(error||!data)redirect("/admin?error="+encodeURIComponent(error?.message||"No se pudo crear la landing"));redirect("/admin/landings/"+data.id+"?saved=Landing creada")}

export async function publish(fd:FormData){const {s,user}=await auth();const id=String(fd.get("id")||"");const returnTo=String(fd.get("return_to")||"/admin");const target=returnTo.startsWith("/admin")?returnTo:"/admin";const desired=String(fd.get("published"))==="true";const {data:landing,error:lookupError}=await s.from("landings").select("id").eq("id",id).eq("owner_id",user.id).maybeSingle();if(lookupError)redirect(target+"?error="+encodeURIComponent(lookupError.message));if(!landing)redirect(target+"?error=Landing inexistente o sin permisos");const {error}=await s.from("landings").update({published:desired}).eq("id",id).eq("owner_id",user.id);if(error)redirect(target+"?error="+encodeURIComponent(error.message));redirect(target+"?saved="+(desired?"Landing publicada":"Landing despublicada"))}
export async function deleteLanding(fd:FormData){const {s,user}=await auth();const id=String(fd.get("id")||"");const {data:landing,error:lookupError}=await s.from("landings").select("id").eq("id",id).eq("owner_id",user.id).maybeSingle();if(lookupError)redirect("/admin?error="+encodeURIComponent(lookupError.message));if(!landing)redirect("/admin?error=Landing inexistente o sin permisos");const {error}=await s.from("landings").delete().eq("id",id).eq("owner_id",user.id);if(error)redirect("/admin?error="+encodeURIComponent(error.message));redirect("/admin?saved=Landing eliminada correctamente")}
