import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { updateClient } from "../../actions";
import { IconEdit, IconFileText } from "@/components/icons";
import Toast from "@/components/toast";
import { Suspense } from "react";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: client } = await supabase.from("clients").select("*").eq("id", id).maybeSingle(); if (!client) notFound(); const { data: landings } = await supabase.from("landings").select("*").eq("client_id", id).order("created_at", { ascending: false });
  return <main className="shell"><Suspense fallback={null}><Toast /></Suspense><header className="builder-header"><Link className="back-link" href="/admin">← Volver</Link><div><p className="eyebrow">Cliente</p><h1>{client.name}</h1></div></header><div className="admin-sections"><section className="card form-card"><div className="section-heading"><span className="step">01</span><div><h2>Identidad</h2><p className="muted">Datos y colores del cliente.</p></div></div><form action={updateClient} className="stack"><input type="hidden" name="id" value={id} /><label className="label">Nombre del negocio<input name="name" defaultValue={client.name} required /></label><label className="label">Email<input name="email" type="email" defaultValue={client.email} /></label><label className="label">WhatsApp<input name="phone" defaultValue={client.phone} /></label><div className="form-split"><label className="label">Color principal<input name="primary_color" type="color" defaultValue={client.primary_color || "#1f2937"} /></label><label className="label">Color de fondo<input name="background_color" type="color" defaultValue={client.background_color || "#f7f5f0"} /></label></div><button className="btn full" type="submit">Guardar cambios</button></form></section><section className="card form-card"><div className="section-heading"><span className="step">02</span><div><h2>Landings</h2><p className="muted">{landings?.length || 0} experiencias creadas.</p></div></div><div className="entity-list">{!landings?.length && <div className="empty-state"><IconFileText /><strong>Este cliente todavía no tiene landings</strong><p className="muted">Creá una desde el panel principal.</p></div>}{landings?.map((landing) => <div className="landing-row" key={landing.id}><div><strong>{landing.business_name}</strong><span className={landing.published ? "status published" : "status"}>{landing.published ? "Publicada" : "Borrador"}</span></div><Link className="icon-text-button accent" href={`/admin/landings/${landing.id}/editor-v2`}><IconEdit /> Editar</Link></div>)}</div></section></div></main>;
}
